default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: levee_development


test:
  <<: *default
  database: levee_test


# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: levee-backend_development
#   username: postgres
#   password: postgres
#   host: localhost

# test:
#   <<: *default
#   database: levee-backend_development

# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>
